env:
  browser: true
  es6: true
  node: true
  jquery: true
extends:
  - 'plugin:vue/essential'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules: {
  "no-extend-native": ["error", { "exceptions": ["Array"] }],
  "semi": ["error", "always"],
  "space-before-function-paren": ["error", "never"],
  "indent": ["off", 4]
}
ignorePatterns: ["lib/"]
